# kubernetes-fastapi LoadBalancer Service
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: kf-api-svc
spec:
  selector:
    app: kf-api
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
# kf-api Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-api
  labels:
    app: kf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kf-api
  template:
    metadata:
      labels:
        app: kf-api
    spec:
      containers:
        - name: kf-api
          image: 127012818163.dkr.ecr.us-east-1.amazonaws.com/argocd:0.0.4
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"