apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-imageupdater-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=127012818163.dkr.ecr.us-east-1.amazonaws.com/argocd:~1
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/myalias.pull-secret: pullsecret:argocd/mycontainerregistry-secret
    argocd-image-updater.argoproj.io/myalias.force-update: "true"

spec:
  project: argocd-imageupdater-project
  source:
    repoURL: https://github.com/ximenesfel/argocd_kubernetes.git
    targetRevision: HEAD
    path: applications/testing/ 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true