apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater

data:
  log.level: debug
  registries.conf: |
    registries:
    - name: ECR
      api_url: https://127012818163.dkr.ecr.us-east-1.amazonaws.com
      prefix: 127012818163.dkr.ecr.us-east-1.amazonaws.com
      default: true
      ping: yes
      insecure: no
      # credentials: ext:/scripts/ecr-login.sh
      credentials: pullsecret:argocd/mycontainerregistry-secret
      credsexpire: 10h
  authScripts: |
    enabled: true
    scripts: 
      ecr-login.sh: |   # notice script name matches above    
        #!/bin/sh
        aws ecr --region us-east-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

