apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  namespace: health-check
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: node-hello-world-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world-deployment
  namespace: health-check
  labels:
    app: node-hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-world-app
  template:
    metadata:
      labels:
        app: node-hello-world-app
    spec:
      containers:
      - name: node-hello-world-app-container
        image: 127012818163.dkr.ecr.us-east-1.amazonaws.com/argocd:0.0.1
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 80
      imagePullSecrets:
          - name: regcred