apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-arm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=127012818163.dkr.ecr.us-east-1.amazonaws.com/argocd:~0.0.1
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/myalias.pull-secret: pullsecret:argocd/mycontainerregistry-secret
    argocd-image-updater.argoproj.io/myalias.force-update: "true"

spec:
  project: argocd-demo
  source:
    repoURL: https://github.com/ximenesfel/argocd_kubernetes.git
    targetRevision: HEAD
    path: nginx-demo/arm/kustomize/overlays/testing
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true