apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-arm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/jjader/jamisson:~0.0.1
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: argocd-demo
  source:
    repoURL: https://github.com/ximenesfel/argocd_kubernetes.git
    targetRevision: HEAD
    path: nginx-demo/arm/kustomize/overlays/testing
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true