apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Demo Project

  sourceRepos:
    #- '*'
    - https://github.com/ximenesfel/argocd_kubernetes.git

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
