apiVersion: v1
kind: Secret
metadata:
  name: argocd-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: argocd-demo
  url: https://github.com/ximenesfel/argocd_kubernetes.git
  password: 
